const scholarship = [
['2026','Funded research','$8M NSF E-RISE / Nebraska Center for 3D Innovation','Co-principal investigator','https://www.unomaha.edu/news/uno-secures-8m-nsf-award-to-establish-nebraska-center-for-3d-innovation.php'],
['2026','Book chapter','Enhancing Interprofessional Healthcare Simulation to Address the Needs of All Patient Populations','Co-author · Springer','https://link.springer.com/book/10.1007/978-3-032-03947-7'],
['2026','Award-recognized scholarship','Implementing Holographic Instruction in Multi-Campus DPT Education','Co-author · Second Place Outstanding Project Award','https://www.unmc.edu/academy/scholarship/spotlight.html'],
['2025','Publication','The Current State and Future of Haptics in Healthcare Simulation','Co-author · Society for Simulation in Healthcare STORM','https://www.ssih.org/sites/default/files/2025-10/STORM-Vol.%204%2C%20Issue%202_0.pdf']
];
const speaking = [
['2026','Digital Hollywood: The AI & Entertainment Summit','Panelist — interactive holography, volumetric media and AI','https://www.digitalhollywood.com/wednesday-twelve---summer-2026-ai-festival'],
['2026','University of Miami Digital EyeCon','Workshop + invited presentations on AI, XR and future learning environments','https://news.med.miami.edu/digital-eyecon-2026-ai-remote-patient-monitoring/'],
['2026','University of Georgia Healthcare 5.0','Presenter — immersive technology and health professions education','https://rx.uga.edu/event/healthcare-5-0-driving-precision-health-and-education-through-immersive-technology-and-artificial-intelligence/'],
['2026','International Meeting on Simulation in Healthcare','Panelist — evidence, challenges and strategies for haptics','https://imsh2026.org/sites/default/files/2026-01/2026%20IMSH%20DIGITAL%20PROGRAM%20BOOK-opt_0.pdf'],
['2024','The Generalists in Medical Education','National keynote co-presenter — implementing change in traditional settings','https://thegeneralists.org/wp-content/uploads/2024/11/TGME_Program_2024.pdf']
];
export default function Home(){return <main>
<header className="top"><a className="brand" href="#top"><b>MH</b><span>Michael Hollins<small>Living career archive</small></span></a><nav><a href="#work">Work</a><a href="#kaneko">KANEKO</a><a href="#pace">PACE</a><a href="#research">Research</a><a href="#speaking">Speaking</a></nav></header>
<section id="top" className="hero"><img className="heroPhoto" src="/media/hero.webp" alt="Michael Hollins at UNMC Davis Global Center"/><div className="shade"></div><div className="wrap heroCopy"><p className="eyebrow light">Executive leadership · technology · scholarship · community</p><h1>Omaha roots.<br/>National reach.</h1><p className="lead">Omaha-grown interdisciplinary executive, faculty member and scholar-practitioner building connections across creative leadership, emerging technology, health professions education, research, business development and community impact.</p><div className="buttons"><a className="btn lime" href="#work">Explore the career archive</a></div></div><div className="photoTag">Michael Hollins · UNMC Davis Global Center · 2024</div></section>
<section className="metrics wrap"><div><b>$8M</b><span>NSF E-RISE initiative</span></div><div><b>12</b><span>KANEKO exhibition seasons</span></div><div><b>5,500+</b><span>Common Senses attendees</span></div><div><b>55.2M</b><span>Potential media impressions</span></div></section>
<section id="work" className="section wrap"><div className="heading"><div><p className="eyebrow">Selected work</p><h2>A career built at the intersections.</h2></div><p>The archive is designed to show the work, not just list it: institutions built, technologies translated, communities connected and ideas brought into public life.</p></div><div className="featureGrid"><article><span>2019–present</span><h3>UNMC iEXCEL</h3><p>Executive leadership in creative production, emerging technology, business development, statewide education, research, external relations and advancement.</p></article><article><span>2026–present</span><h3>Nebraska Center for 3D Innovation</h3><p>Co-principal investigator on NSF Award No. 2546319 supporting an $8 million statewide E-RISE initiative.</p></article><article><span>2023–present</span><h3>Statewide & rural health education</h3><p>Holography, VR, connected 3D iWalls and multi-site production used to reduce geographic barriers across Nebraska.</p></article></div></section>
<section id="kaneko" className="chapter dark"><div className="wrap"><div className="chapterIntro"><div><p className="eyebrow aqua">KANEKO · 2013–2018</p><h2>Curating across art, science, design and emerging technology.</h2></div><p>Across twelve thematic seasons, Hollins combined exhibition leadership with public programming, youth education, media, design collaboration and increasingly immersive technology.</p></div><div className="mosaic"><figure className="wide"><img src="/media/kaneko_design_in_motion.webp" alt="Michael Hollins leading a Design in Motion youth workshop at KANEKO"/><figcaption><b>Design in Motion</b><span>Youth workshop and hands-on design engagement</span></figcaption></figure><figure><img src="/media/kaneko_water.webp" alt="Michael Hollins teaching students during WATER at KANEKO"/><figcaption><b>WATER</b><span>Gallery teaching and public education</span></figcaption></figure><figure><img src="/media/kaneko_passion.webp" alt="Michael Hollins teaching students during Passion and Obsession at KANEKO"/><figcaption><b>Passion & Obsession</b><span>Connecting students with exhibition ideas</span></figcaption></figure><figure className="wide"><img src="/media/kaneko_reality_1.webp" alt="Michael Hollins presenting during Reality at KANEKO"/><figcaption><b>Reality</b><span>Public programming at the convergence of VR, holography, art and science</span></figcaption></figure><figure><img src="/media/kaneko_reality_2.webp" alt="Michael Hollins presenting on stage during Reality at KANEKO"/><figcaption><b>Reality</b><span>Speaking across art, science and emerging technology</span></figcaption></figure><figure><img src="/media/kaneko_google_ai.webp" alt="Michael Hollins introducing a presentation on artificial intelligence by Chris Russell of Google during Reality at KANEKO"/><figcaption><b>Artificial intelligence at Reality</b><span>Introducing Chris Russell of Google for a public program on AI</span></figcaption></figure></div></div></section>
<section id="pace" className="chapter pace"><div className="wrap"><div className="chapterIntro"><div><p className="eyebrow">PACE · 2018–2019</p><h2>Building an organization while the building itself was taking shape.</h2></div><p>Recruited during development of the nearly $27 million, 95,000-square-foot Hoff Family Arts & Culture Center, Hollins contributed to organizational structure, programming strategy, facility functions, public identity and the design-development process.</p></div><div className="paceGrid three"><figure><img src="/media/pace_owh.webp" alt="Michael Hollins at the Hoff Center construction site in a photograph published by the Omaha World-Herald"/><figcaption>Hoff Center construction · originally published by the Omaha World-Herald</figcaption></figure><figure><img src="/media/pace_site.webp" alt="Michael Hollins at the Hoff Center construction site"/><figcaption>Construction-site design and facility development</figcaption></figure><figure><img src="/media/pace_headshot.webp" alt="Michael Hollins in PACE construction helmet during the design phase"/><figcaption>PACE design phase · Council Bluffs</figcaption></figure></div></div></section>
<section id="research" className="section wrap"><div className="heading"><div><p className="eyebrow">Research & scholarship</p><h2>From implementing technology to studying how it should be used.</h2></div></div><div className="records">{scholarship.map(s=><a href={s[4]} target="_blank" rel="noreferrer" key={s[2]}><span>{s[0]}</span><div><small>{s[1]}</small><h3>{s[2]}</h3><p>{s[3]}</p></div><b>↗</b></a>)}</div></section>
<section id="speaking" className="soft section"><div className="wrap"><div className="heading"><div><p className="eyebrow">National voice</p><h2>Speaking where health, technology, education and media converge.</h2></div></div><div className="records">{speaking.map(s=><a href={s[3]} target="_blank" rel="noreferrer" key={s[1]}><span>{s[0]}</span><div><small>Forum</small><h3>{s[1]}</h3><p>{s[2]}</p></div><b>↗</b></a>)}</div></div></section>
<footer><div className="wrap"><div><p className="eyebrow aqua">Living career archive</p><h2>Michael Hollins</h2><p>Assistant Vice Chancellor · Assistant Professor · UNMC<br/>Omaha, Nebraska</p></div><div><a href="mailto:michael.hollins@unmc.edu">michael.hollins@unmc.edu</a><a href="https://www.linkedin.com/in/michael-hollins-70463371/">LinkedIn ↗</a></div></div></footer>
</main>}
